### ISSUE TITLE
a floating point issue in checking the probability of emission matrix

### ISSUE THREAD

**Issue by f-rumblefish** [Red-devilz/hmm_project#7]
Dear Red-devilz:

If we set the probability of emission matrix as

`emission_probability = np.matrix('0.1 0.4 0.5 ; 0.6 0.3 0.1')`

the above statement will results in the following error:

`ValueError: Probabilities entered for emission matrix are invalid`

After checking the source code, I find that 

- the sum of "0.1, 0.4, and 0.5" is 1.0, but 
- the sum of "06, 0.3, and 0.1" is 0.99999999999999989,

The precision of the second case fails at comparing tmp1/tmp2 in Lin82 in hmm_class.py.

Please provide your advice on this issue. Thanks!

p.s. My system is Python (2.7.11) and Numpy (1.11.2) on Windows 10.

**Comment by rahul13ramesh** [comment]
Hey,

You are right. It's not a great idea to check for exact equality. Hence I have now changed to code to use [numpy.isclose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.isclose.html). If you still get an error, you can fiddle around with the _atoi_  and _rtoi_ parameters   in numpy.isclose to have looser bounds.

On a side note, you can consider checking out  [https://github.com/Red-devilz/hidden_markov](https://github.com/Red-devilz/hidden_markov). This repository is a pip package with better documented code and uses scaling(i.e Log scale is used to prevent underflow). 

Links to Documentation and Pip Package : 
*  [Hidden markov documentation](http://hidden-markov.readthedocs.io/en/latest/)
* [pip package](https://pypi.python.org/pypi/hidden_markov/0.3.2)

**Comment by f-rumblefish** [comment]
Dear Red-devilz:

Thanks for quick reply. Problem solved. 

Regards
